name: Run Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Python نصب
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: نصب کتابخونه‌ها
        run: |
          pip install ccxt pandas

      - name: اجرای کد
        run: python bot.py
